DROP TABLE IF EXISTS TB_SALDO_DA_EMPRESA;
DROP TABLE IF EXISTS TB_SALDO_DA_EMPRESA_HISTORICO;

CREATE TABLE TB_SALDO_DA_EMPRESA(
	id INTEGER NOT NULL AUTO_INCREMENT,
	valor_em_reais_total  DECIMAL(10,2) NOT NULL,
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL ON UPDATE CURRENT_TIMESTAMP(3),
	PRIMARY KEY (`id`) 
)DEFAULT CHARACTER SET utf8mb4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE TB_SALDO_DA_EMPRESA_HISTORICO(
    id INTEGER NOT NULL AUTO_INCREMENT,
	valor_em_reais_transacao DECIMAL(10,2) NOT NULL,
	porcentagem_transacao INT NOT NULL,
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`)
)DEFAULT CHARACTER SET utf8mb4 COLLATE UTF8MB4_UNICODE_CI;


CREATE TABLE TB_SALDO_DO_ACUMULATIVO(
	id INTEGER NOT NULL AUTO_INCREMENT,
	valor_em_reais_total  DECIMAL(10,2) NOT NULL,
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL ON UPDATE CURRENT_TIMESTAMP(3),
	PRIMARY KEY (`id`) 
)DEFAULT CHARACTER SET utf8mb4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE TB_SALDO_DO_ACUMULATIVO_HISTORICO(
    id INTEGER NOT NULL AUTO_INCREMENT,
	valor_em_reais_transacao DECIMAL(10,2) NOT NULL,
	porcentagem_transacao INT NOT NULL,
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`)
)DEFAULT CHARACTER SET utf8mb4 COLLATE UTF8MB4_UNICODE_CI;