

DROP PROCEDURE IF EXISTS PROCEDURE_ATUALIZA_VALORES_DE_PORCENTAGEM_E_VALOR_APOSTA;


DELIMITER //
CREATE PROCEDURE PROCEDURE_ATUALIZA_VALORES_DE_PORCENTAGEM_E_VALOR_APOSTA(
		IN INPUT_TIPO_CALCULO VARCHAR(50),
		IN INPUT_VALOR_APOSTA VARCHAR(50)
		)

BEGIN
   
   IF INPUT_TIPO_CALCULO = 'UPDATE_VALOR_CADA_APOSTA' THEN	 
   	UPDATE TB_BUSCAR_PORCENTAGEM SET FIELD_VALOR_CADA_APOSTA = CAST(INPUT_VALOR_APOSTA AS DECIMAL(10,2))   WHERE id = 1;   	
		SELECT * FROM TB_BUSCAR_PORCENTAGEM WHERE id = 1;
   	
   	
   ELSEIF INPUT_TIPO_CALCULO = 'UPDATE_VALOR_PORCENTAGEM_CASA_ACUMULATIVO' THEN
   	UPDATE TB_BUSCAR_PORCENTAGEM SET FIELD_VALOR_PORCENTAGEM_CASA_ACUMULATIVO = CAST(INPUT_VALOR_APOSTA AS INT)   WHERE id = 1;
   	SELECT * FROM TB_BUSCAR_PORCENTAGEM WHERE id = 1;
   	
   	
   ELSEIF INPUT_TIPO_CALCULO = 'UPDATE_VALOR_PORCENTAGEM_CASA' THEN
      -- LUCRO DE CADA RODADA PARA O ZÉ
      UPDATE TB_BUSCAR_PORCENTAGEM SET FIELD_VALOR_PORCENTAGEM_CASA = CAST(INPUT_VALOR_APOSTA AS INT)   WHERE id = 1;
   	SELECT * FROM TB_BUSCAR_PORCENTAGEM WHERE id = 1;
   	
   	
   ELSEIF INPUT_TIPO_CALCULO = 'UPDATE_VALOR_PORCENTAGEM_PARA_JOGO' THEN
   	-- VALOR REATRIBUIDO PARA OS JOGADORES INCREMENTAÇÃO
   	UPDATE TB_BUSCAR_PORCENTAGEM SET FIELD_VALOR_PORCENTAGEM_PARA_JOGO = CAST(INPUT_VALOR_APOSTA AS INT)   WHERE id = 1;
  		SELECT * FROM TB_BUSCAR_PORCENTAGEM WHERE id = 1;
  		
  	 ELSE
	   SELECT 'O VALOR DO TIPO PASSADO NÃO É ATRIBUIDO A NENHUMA TOMADA DE DECISÃO NA PROCEDURE PROCEDURE_ATUALIZA_VALORES_DE_PORCENTAGEM_E_VALOR_APOSTA' AS ERRORSQL;
   END IF;
   
END //

DELIMITER ;


CALL PROCEDURE_ATUALIZA_VALORES_DE_PORCENTAGEM_E_VALOR_APOSTA('UPDATE_VALOR_PORCENTAGEM_CASA','15')
