DROP PROCEDURE IF EXISTS PROCEDURE_BUSCAR_VALORES_A_SER_PAGO;


DELIMITER $$
CREATE PROCEDURE PROCEDURE_BUSCAR_VALORES_A_SER_PAGO(IN INPUT_ID INT)
		
		BEGIN			
				SELECT * FROM awards WHERE awards.id = INPUT_ID;
		END $$

DELIMITER ;

CALL PROCEDURE_BUSCAR_VALORES_A_SER_PAGO(110);