DROP PROCEDURE IF EXISTS PROCEDURE_BUSCAR_GANHADORES_POR_ESTABELECIMENTO_E_CONCURSO;

DELIMITER //
CREATE PROCEDURE PROCEDURE_BUSCAR_GANHADORES_POR_ESTABELECIMENTO_E_CONCURSO(
	IN INPUT_ESTABELECIMENTO_ID INT,
	IN INPUT_NUMBER_GAME_RESULT INT
)

BEGIN
   DECLARE RESULTADO VARCHAR(255);
   SELECT *  FROM  bets AS B WHERE  B.hits >= 4 AND B.`status` = 'FINISHED' AND B.establishmentId = INPUT_ESTABELECIMENTO_ID AND B.number_game_result = INPUT_NUMBER_GAME_RESULT;
END //

DELIMITER ;

CALL PROCEDURE_BUSCAR_GANHADORES_POR_ESTABELECIMENTO_E_CONCURSO(2,6)