DROP PROCEDURE IF EXISTS PROCEDURE_BUSCAR_GANHADORES_POR_ESTABELECIMENTO_E_TODOS;

DELIMITER //
CREATE PROCEDURE PROCEDURE_BUSCAR_GANHADORES_POR_ESTABELECIMENTO_E_TODOS(IN INPUT_ESTABELECIMENTO_ID INT)

BEGIN
   DECLARE RESULTADO VARCHAR(255);
   SELECT *  FROM  bets AS B WHERE  B.hits >= 4 AND B.`status` = 'FINISHED' AND B.establishmentId = INPUT_ESTABELECIMENTO_ID;
END //

DELIMITER ;

CALL PROCEDURE_BUSCAR_GANHADORES_POR_ESTABELECIMENTO_E_TODOS(2)