


DROP PROCEDURE IF EXISTS PROCEDURE_REGISTRAR_JOGOS;

DELIMITER //
CREATE PROCEDURE PROCEDURE_REGISTRAR_JOGOS(
	IN INPUT_ESTABELECIMENTO_ID INT,
	IN	INPUT_NUMEROS_DO_JOGO INT,
	IN INPUT_CODE_CART VARCHAR(100)
)

BEGIN
   DECLARE _NUMEROS VARCHAR(191);
   DECLARE _CLEAN VARCHAR(191);
   DECLARE ULTIMO_NUMERO_DO_JOGO_REGISTRADO INT;   
	
   CALL PROCIDURE_GERAR_NUMEROS_ALEATORIOS(_NUMEROS,INPUT_NUMEROS_DO_JOGO);
	
    SELECT(G.id + 1) INTO ULTIMO_NUMERO_DO_JOGO_REGISTRADO FROM games AS G ORDER BY G.id DESC LIMIT 1;		
	 INSERT INTO bets (establishmentId,number_game_result,numbers,code_cart) VALUES (INPUT_ESTABELECIMENTO_ID,IFNULL(ULTIMO_NUMERO_DO_JOGO_REGISTRADO,1),_NUMEROS,INPUT_CODE_CART);	
   SELECT * FROM bets WHERE establishmentId = INPUT_ESTABELECIMENTO_ID AND number_game_result = IFNULL(ULTIMO_NUMERO_DO_JOGO_REGISTRADO,1) AND `status` = 'IN_PROCESSING' AND code_cart= INPUT_CODE_CART; 
    SELECT INPUT_CODE_CART;
END //

DELIMITER ;

CALL PROCEDURE_REGISTRAR_JOGOS(2,25,'BC407EE4-F645-4BE8-89F8-EDD6FCFA5D38');