CREATE TABLE TB_BUSCAR_PORCENTAGEM (
    id INTEGER NOT NULL AUTO_INCREMENT,
    FIELD_VALOR_CADA_APOSTA  DECIMAL(10,2) DEFAULT 2.00,
    FIELD_VALOR_PORCENTAGEM_CASA_ACUMULATIVO INT(11) DEFAULT 5,
    FIELD_VALOR_PORCENTAGEM_CASA INT(11) DEFAULT 25,
    FIELD_VALOR_PORCENTAGEM_PARA_JOGO INT(11) DEFAULT 70,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL ON UPDATE CURRENT_TIMESTAMP(3), 
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;