
DELIMITER //
CREATE TRIGGER TRIGER_INSERT_TRANSACTION AFTER INSERT ON transactions 
FOR EACH ROW 

BEGIN
		DECLARE SET_IS_COMPLETED VARCHAR(100);
		DECLARE SET_SUBTRACT_PREMIUMS DECIMAL(10,2);
		DECLARE SET_AMOUNT_ACAUMULATED DECIMAL(10,2);
		DECLARE SET_AMOUNT DECIMAL(10,2);
		DECLARE VIEW_MONTANTE DECIMAL(10,2);
		
		DECLARE VALORES_PARA_DIVIDIR_AS_PORCENTAGEM DECIMAL(10,2);
		
		SELECT awards.subtract_premiums INTO SET_SUBTRACT_PREMIUMS FROM awards ORDER BY awards.id  DESC LIMIT 1;
      SELECT awards.is_completed INTO SET_IS_COMPLETED FROM awards ORDER BY awards.id  DESC LIMIT 1;	
		
		
		IF SET_IS_COMPLETED = "REFUSES_VALUES" THEN
			SELECT transactions.amount INTO SET_AMOUNT FROM transactions ORDER BY transactions.id DESC LIMIT 1;
			SELECT accumulated.money INTO SET_AMOUNT_ACAUMULATED FROM accumulated WHERE accumulated.id = 1;
			SET VIEW_MONTANTE = SET_AMOUNT + SET_AMOUNT_ACAUMULATED;
			UPDATE accumulated SET money = VIEW_MONTANTE WHERE accumulated.id = 1;
		END IF;
		
		IF SET_IS_COMPLETED = "IN_PROCESSING" THEN
			SELECT accumulated.money INTO SET_AMOUNT_ACAUMULATED FROM accumulated WHERE accumulated.id = 1;			
			UPDATE accumulated SET money = 00.00 WHERE accumulated.id = 1;		
				
			SELECT transactions.amount INTO SET_AMOUNT FROM transactions ORDER BY transactions.id DESC LIMIT 1;
			
			SET VALORES_PARA_DIVIDIR_AS_PORCENTAGEM = SET_AMOUNT_ACAUMULATED + SET_AMOUNT + SET_SUBTRACT_PREMIUMS;		
			
			-- SELECT (120 * 70) / 100
			UPDATE awards SET  awards.subtract_premiums = VALORES_PARA_DIVIDIR_AS_PORCENTAGEM , 
									 awards.seine = (VALORES_PARA_DIVIDIR_AS_PORCENTAGEM * 70 ) / 100,
									 awards.corner = (VALORES_PARA_DIVIDIR_AS_PORCENTAGEM * 15 ) / 100,
									 awards.`block` = (VALORES_PARA_DIVIDIR_AS_PORCENTAGEM * 10 ) / 100
									 WHERE awards.is_completed = 'IN_PROCESSING'; 								 									 
					
		END IF;
		
	END
DELIMITER ;