SELECT * FROM awards LIMIT 1;
DROP VIEW IF EXISTS VIEW_VERIFICAR_SE_EXISTE_PAGAMENTO_IN_PROCESSO;
CREATE VIEW VIEW_VERIFICAR_SE_EXISTE_PAGAMENTO_IN_PROCESSO AS SELECT A.id, A.subtract_premiums FROM awards AS A WHERE A.is_completed = 'IN_PROCESSING' LIMIT 1;
SELECT * FROM VIEW_VERIFICAR_SE_EXISTE_PAGAMENTO_IN_PROCESSO;